services:
  - postgresql
language: python
install:
  - pip install tox
  - pip install coveralls
before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database denorm_test;' -U postgres; fi;"

script:
  - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO}-${DB}

python:
  - "3.8"
  - "3.9"

env:
  - DJANGO=django30 DB=postgres
  - DJANGO=django31 DB=postgres
  - DJANGO=django32 DB=postgres
#  - DJANGO=djangomaster DB=postgres

matrix:
  fast_finish: true
#  allow_failures:
#    - env: DJANGO=djangomaster DB=postgres
after_script:
  - cd test_denorm_project/
  - coveralls --rcfile=../.coveragerc
