[tox]
envlist = {py310,py311,py312,py313}-django42
	{py310,py311,py312,py313}-django52
	{py312,py313}-django60

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313


[testenv]
commands =
    pip install coverage psycopg2
    python runtests.py postgres
    pytest tests/

deps =
    django42: Django>=4.2, <4.3
    django52: Django>=5.2, <5.3
    django60: Django>=6.0, <6.1
    psycopg2
    celery
    celery_singleton
    coverage
    pytest
    pytest-django
    pytest-timeout
