# Generated by Django 6.0.5 on 2026-06-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_alter_callcounter_called_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(default='', max_length=50)),
                ('full_name', models.CharField(editable=False, max_length=101)),
                ('letterhead', models.CharField(editable=False, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileReversed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('letterhead', models.CharField(editable=False, max_length=120)),
                ('full_name', models.CharField(editable=False, max_length=101)),
            ],
        ),
        migrations.CreateModel(
            name='UndeclaredProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(editable=False, max_length=101)),
            ],
        ),
    ]
