# Generated by Django 6.0.6 on 2026-06-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_profile_profilereversed_undeclaredprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlwaysDirtyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('note', models.CharField(default='', max_length=50)),
                ('greeting', models.CharField(editable=False, max_length=60)),
            ],
        ),
    ]
