# Generated by Django 5.2.17 on 2026-08-06 19:40

import denorm.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_alwaysdirtymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2MAggregateTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('tagger_count', denorm.fields.CountField('taggers', default=0)),
                ('tagger_weight_sum', denorm.fields.SumField('taggers', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='M2MAggregateTagger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('targets', models.ManyToManyField(blank=True, related_name='taggers', to='test_app.m2maggregatetarget')),
            ],
        ),
    ]
