# Generated by Django 6.0.6 on 2026-06-12 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('denorm', '0017_dirtyinstance_unique_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirtyinstance',
            name='content_type',
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AlterField(
            model_name='dirtyinstance',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dirtyinstance',
            name='func_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
